package com.ljd.ai.model;

import org.springframework.stereotype.Repository;

public class ImageInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGE_INFO.I_ID
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    private Integer iId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGE_INFO.I_IMAGE_CONVERT_BEFORE_URL
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    private String iImageConvertBeforeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGE_INFO.I_IMAGE_CONVERT_AFTER_URL
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    private String iImageConvertAfterUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGE_INFO.I_ID
     *
     * @return the value of IMAGE_INFO.I_ID
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGE_INFO.I_ID
     *
     * @param iId the value for IMAGE_INFO.I_ID
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGE_INFO.I_IMAGE_CONVERT_BEFORE_URL
     *
     * @return the value of IMAGE_INFO.I_IMAGE_CONVERT_BEFORE_URL
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public String getiImageConvertBeforeUrl() {
        return iImageConvertBeforeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGE_INFO.I_IMAGE_CONVERT_BEFORE_URL
     *
     * @param iImageConvertBeforeUrl the value for IMAGE_INFO.I_IMAGE_CONVERT_BEFORE_URL
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public void setiImageConvertBeforeUrl(String iImageConvertBeforeUrl) {
        this.iImageConvertBeforeUrl = iImageConvertBeforeUrl == null ? null : iImageConvertBeforeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGE_INFO.I_IMAGE_CONVERT_AFTER_URL
     *
     * @return the value of IMAGE_INFO.I_IMAGE_CONVERT_AFTER_URL
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public String getiImageConvertAfterUrl() {
        return iImageConvertAfterUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGE_INFO.I_IMAGE_CONVERT_AFTER_URL
     *
     * @param iImageConvertAfterUrl the value for IMAGE_INFO.I_IMAGE_CONVERT_AFTER_URL
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public void setiImageConvertAfterUrl(String iImageConvertAfterUrl) {
        this.iImageConvertAfterUrl = iImageConvertAfterUrl == null ? null : iImageConvertAfterUrl.trim();
    }
}