package com.ljd.ai.model;

import java.util.ArrayList;
import java.util.List;

public class ImageInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public ImageInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIIdIsNull() {
            addCriterion("I_ID is null");
            return (Criteria) this;
        }

        public Criteria andIIdIsNotNull() {
            addCriterion("I_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIIdEqualTo(Integer value) {
            addCriterion("I_ID =", value, "iId");
            return (Criteria) this;
        }

        public Criteria andIIdNotEqualTo(Integer value) {
            addCriterion("I_ID <>", value, "iId");
            return (Criteria) this;
        }

        public Criteria andIIdGreaterThan(Integer value) {
            addCriterion("I_ID >", value, "iId");
            return (Criteria) this;
        }

        public Criteria andIIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_ID >=", value, "iId");
            return (Criteria) this;
        }

        public Criteria andIIdLessThan(Integer value) {
            addCriterion("I_ID <", value, "iId");
            return (Criteria) this;
        }

        public Criteria andIIdLessThanOrEqualTo(Integer value) {
            addCriterion("I_ID <=", value, "iId");
            return (Criteria) this;
        }

        public Criteria andIIdIn(List<Integer> values) {
            addCriterion("I_ID in", values, "iId");
            return (Criteria) this;
        }

        public Criteria andIIdNotIn(List<Integer> values) {
            addCriterion("I_ID not in", values, "iId");
            return (Criteria) this;
        }

        public Criteria andIIdBetween(Integer value1, Integer value2) {
            addCriterion("I_ID between", value1, value2, "iId");
            return (Criteria) this;
        }

        public Criteria andIIdNotBetween(Integer value1, Integer value2) {
            addCriterion("I_ID not between", value1, value2, "iId");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlIsNull() {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL is null");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlIsNotNull() {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlEqualTo(String value) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL =", value, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlNotEqualTo(String value) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL <>", value, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlGreaterThan(String value) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL >", value, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL >=", value, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlLessThan(String value) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL <", value, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlLessThanOrEqualTo(String value) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL <=", value, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlLike(String value) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL like", value, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlNotLike(String value) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL not like", value, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlIn(List<String> values) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL in", values, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlNotIn(List<String> values) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL not in", values, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlBetween(String value1, String value2) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL between", value1, value2, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertBeforeUrlNotBetween(String value1, String value2) {
            addCriterion("I_IMAGE_CONVERT_BEFORE_URL not between", value1, value2, "iImageConvertBeforeUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlIsNull() {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL is null");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlIsNotNull() {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL is not null");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlEqualTo(String value) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL =", value, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlNotEqualTo(String value) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL <>", value, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlGreaterThan(String value) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL >", value, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlGreaterThanOrEqualTo(String value) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL >=", value, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlLessThan(String value) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL <", value, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlLessThanOrEqualTo(String value) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL <=", value, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlLike(String value) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL like", value, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlNotLike(String value) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL not like", value, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlIn(List<String> values) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL in", values, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlNotIn(List<String> values) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL not in", values, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlBetween(String value1, String value2) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL between", value1, value2, "iImageConvertAfterUrl");
            return (Criteria) this;
        }

        public Criteria andIImageConvertAfterUrlNotBetween(String value1, String value2) {
            addCriterion("I_IMAGE_CONVERT_AFTER_URL not between", value1, value2, "iImageConvertAfterUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 30 17:57:45 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IMAGE_INFO
     *
     * @mbg.generated Tue Mar 30 17:57:45 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}